#%%
combined_symptoms = [
    "weight loss","chills","shivering","convulsions","deformity","discharge","dizziness", "lymphopenia", "sneezing",
    "vertigo","fatigue","malaise","asthenia","hypothermia","jaundice","muscle weakness", "chest discomfort",
    "pyrexia","sweats","swelling","swollen","painful lymph node","weight gain","arrhythmia", "loss of smell",
    "loss of appetite", "loss of taste", "bradycardia","chest pain","claudication","palpitations","tachycardia",
    "dry mouth","epistaxis", "dysgeusia", "hypersomnia", "taste loss", "halitosis","hearing loss","nasal discharge",
    "nasal inflammation", "otalgia","otorrhea","sore throat","toothache","tinnitus", "dysphonia",
    "trismus","abdominal pain","fever","bloating","belching","bleeding","bloody stool","melena","hematochezia",
    "burning sensation in the chest", "constipation","diarrhea","dysphagia","dyspepsia","fecal incontinence",
    "flatulence", "heartburn", "chest tightness", "chest pressure","nausea","odynophagia","proctalgia fugax",
    "pyrosis","steatorrhea","vomiting","alopecia","hirsutism", "tachypnoea", "nasal obstruction",
    "hypertrichosis","abrasion","anasarca","bleeding into skin","petechia","purpura","ecchymosis", "bruising",
    "blister","edema","itching","laceration","rash","urticaria","abnormal posturing","acalculia","agnosia","alexia",
    "amnesia","anomia","anosognosia","aphasia","apraxia","ataxia","cataplexy","confusion","dysarthria",
    "nasal congestion","dysdiadochokinesia","dysgraphia","hallucination","headache","akinesia","bradykinesia",
    "ballismus","blepharospasm","chorea","dystonia","fasciculation","muscle cramps","myoclonus","opsoclonus",
    "tremor","flapping tremor","insomnia","loss of consciousness","syncope","neck stiffness","opisthotonus",
    "paralysis","paresis","paresthesia","prosopagnosia","somnolence","abnormal vaginal bleeding", "neuralgia",
    "vaginal bleeding in early pregnancy", "miscarriage","vaginal bleeding in late pregnancy","amenorrhea", "body aches",
    "infertility","painful intercourse","pelvic pain","vaginal discharge","amaurosis fugax","amaurosis", "skin lesions",
    "blurred vision","double vision","exophthalmos","mydriasis","miosis","nystagmus","amusia","anhedonia",
    "anxiety","apathy","confabulation","depression","delusion","euphoria","homicidal ideation","irritability",
    "mania","paranoid ideation","suicidal ideation","apnea","hypopnea","cough","dyspnea","bradypnea","tachypnea",
    "orthopnea","platypnea","trepopnea","hemoptysis","pleuritic chest pain","sputum production","arthralgia",
    "back pain","sciatica","urologic","dysuria","hematospermia","hematuria","impotence","polyuria",
    "retrograde ejaculation","strangury","urethral discharge","urinary frequency","urinary incontinence",
    "anosmia", "myalgia", "rhinorrhea", "shortness of breath", "difficulty breathing", "muscle ache", "congestion",
    "runny nose", "trouble breathing", "persistent pain", "pressure in the chest", "inability to wake", "stay awake",
    "bluish lips", "bluish face","akathisia","athetosis", "urinary retention", "fevers",
    "decreased appetite",'relapse', 'anxiety', 'fatigued', 'wanting to sleep', 'weird pressure around my head',
    'feels like', 'pressure around my head and temples and even underneath my jaw and above my nose bridge',
    'water in my ear', 'tension headache', 'head hurts', 'constant pressure all around rather than pain',
    'pressure in your head', 'head rarely hurts', 'brain inflammation', 'headache', 'coughing', 'anxious',
    'breath a little better', 'no fever', 'no chills', 'slight cough', 'cough', 'oxygen levels were good',
    'i was stable', 'i was released', 'helped me with my breathing', 'helps breathing',
    'suffering from shortness of breath', 'breathing gets better', 'very difficult time breathing',
    'choking cough', 'super weak', 'could not breathe', 'collapsed', 'totally exhausts', 'drop my oxygen sat rates',
    'fatigues', 'weak', 'short of breath', 'got so weak', 'lower immune status', 'malaise', 'extreme fatigue',
    'loss of smell', 'poor cognitive thinking', 'shortness of breath', 'cough is still present and exhausting',
    'sense of smell has returned', 'thinking is still slow', 'headaches', 'fatigue', 'cognitive thinking was all but gone',
    'breathing is still stressed', 'thinking and reaction is still slow', 'energy level is almost 0',
    'teeth have also suffered', 'sore throat', 'body aches and chills', 'aches were very painful',
    'every joint in my body hurt', 'able to smell', 'annoying headache', 'not being able to smell', 'exhausting cough',
    'tired', 'feel very alone', 'shortness', 'throat', 'never had much trouble in the way of breathing', 'chills',
    'fevers', 'bad body aches no congestion', 'feeling the shivers', 'sour stomach feeling', 'coughing is exhausting',
    'struggling with coughing', 'exhaustion', 'breathing is difficult', 'body temperature has not been above 97',
    'burning hot', 'temperature not leveled back out little nervous', 'dry cough', 'heaviness in my chest', 'fever',
    'slight headache', 'little but heaviness in my left lung', 'prolonged cough', 'gi discomfort', 'pressure in my chest',
    'nervous', 'collapsed lung', 'cough up', 'help with the breathing', 'it sort of " came back "', 'started to cough',
    'caused some inflammation', 'cant breathe', 'causing an infection in my chest', 'bunged up feeling in my head',
    'strange mild burning sensation in the top of my chest', 'incredibly dry mouth', 'incredibly dry throat',
    'odd taste in my mouth', 'burning sensation', 'incredibly anxious', 'dyspepsia', 'rumbling stomach',
    'burning sensation at the top of my stomach', 'burning sensation to the sides of the lower back',
    'mild burning sensation', 'high temperatures', 'elevated temperature', 'dry cough difficulty breathing',
    'infection', 'woke up with a temperature', 'flu', 'anxiety attack', 'stress', 'coughs', 'sneezes', 'sneeze',
    'stomach up set', 'sweats', 'chest is still heavy', 'weakness', 'joint pain', 'needing more sleep', 'mild headache',
    'running nose', 'some coughing', 'body ache', 'aches', 'sneezing', 'upset stomach', 'night sweats', 'thirsty',
    'lost my breath', 'head was hurting', 'entire body became hot', 'threw up', 'mild sore throat', 'sore throat lozenges',
    'breathing problems', 'sleep apnea', 'respiratory failure', 'weird sensations', 'temperature has been up and down',
    'severe neuropathy', 'seizures', 'symptoms', 'sleep is terrible', 'blood oxygen', 'temperature', 'pulse',
    'oxygen levels', 'temperature was still up', 'bed ridden', 'dizzy', 'breathlessness', 'being so ill', 'light headed',
    'feeling lungs are clogged up', 'feeling of lighting going thru my eyes', 'get blurry', 'high temperature', 'lethargy',
    'burning effect of the nose and surrounding nasal tissue', 'dry mouth', 'chronic fatigue',
    'pins and needles in my forearms right to my fingers', 'numbness', 'cloudy thinking', 'anxiety attacks',
    'brain fog', 'sinus pain', 'nasal congestion', 'loss sense of smell', 'mild cough', 'temp', 'weird dreams',
    'loss sense of taste', 'lost sense of smell', 'chest pain', 'no smell or taste',
    'loss sense of smell , taste , or both', 'head pain', 'abdominal pain all over the stomach',
    'nerves are really bad', 'weird stuff showing up on my skin', 'taste and smell loss', 'feeling',
    'heart grating weak muscles', 'breath', 'shortness of mild headaches', 'loss of appetite', 'feel really ill',
    'nauseous', 'abdominal pains', 'no appetite', 'feel tight chested', 'feel phlegm', 'chest tightness', 'dry nose',
    'mild cramps', 'difficultly breathing', 'swelling', 'chest or ribs are still paining little', 'covid - 19',
    'congestion', 'low grade fever', 'pain in my throat and lymph nodes', 'sore , tight throat', 'blocked nose',
    'hayfever', 'gi symptoms', 'lack of appetite', 'lack of taste and smell', 'tiredness', 'extreme anxiety',
    'neurological symptoms', 'visual disturbances', 'dizziness', 'headache in frontal part of the brain',
    'tingling in my hands and feet', 'stomach pains', 'vomiting', 'bowel issues', 'tight neck', 'tinnitus',
    'vertigo', 'sore , itchy soft palette', 'ear itching', 'shortness of breathe', 'severe headaches',
    'tightness , heaviness on my chest', 'tightness in my chest', 'breathless', 'nausea', 'diarrhea',
    'gastric issues', 'feeling like food is coming up my oesophagus', 'dry throat', 'intense upper back pain',
    'muscle pain', 'neck pain', 'fast heart rate', 'sensations in left side of my face', 'pins and needles in my hands',
    'feels like pain in my bone in my lower leg', 'stinging', 'teary eyes', 'stomach pain', 'pain in my back',
    'muscle pain in my arms', 'pain in my joints', 'tension in my upper body', "feels like i can ' t get a deep breath",
    'i can barely move', 'chest pains', 'feeling that somebody is sat on my back', 'crackly breath',
    'issues with digestive system', 'lung issues', 'severe headache', 'bp was quite elevated', 'elevated bp',
    'one tonsil slightly bigger than the other', 'tongue also feels a little bigger',
    'neck feels like i have pressure on it', 'tight feelings in my chest', 'widespread rash', 'nasal stuffiness',
    'low grade extreme fatigue', 'feel so high temperature', 'sudden wakes up', 'burning the back of my chest',
    'insomnia', 'problems sleeping', 'complete no sleep', 'severe gi symptoms', 'rumbling tummy', 'acid reflux',
    'sense of smell and taste has been really weird', 'most things taste vile', 'smells have changed', 'slight fever',
    'severe fever tastebuds completely gone', 'feverish', 'upper back pain', 'rash', 'silent rumble',
    'thick , odorless mucus', 'suffocating', 'sharp pains behind the neck', 'ache a lot from your back',
    'puffy', 'flu symptoms', 'tight chest', 'no cough', 'no temperature', 'chest started to feel raw and sore',
    'chest started to burn constantly', 'burning', 'burning went down to my tummy shortness of breath', 'catch my breath',
    'heart rate has been through the roof', 'feel dizzy', 'hot night sweats', "i ' m on fire", 'sweating', 'body odour',
    'sweats week', 'body aches', 'high heart rate', 'acute breathlessness', 'severe gastric issues', 'hot sweats',
    'breathing laboured', 'runny nose', 'eyes streaming', 'hay fever', 'winded', 'sore throat', 'breathless', 'taste',
    'loss of smell and pains in chest', 'whole body feels painful', 'chest tightness', 'felt queasy', 'achy',
    'hot to touch', 'low grade temperature', "don ' t want to eat much", 'neck muscles ache', 'struggled to sleep',
    'sleeping is very poor', 'cold like symptoms', 'trouble with sleeping', 'breathing still up and down', 'darts of pain',
    'upper back ache', 'sore', 'raised temperature', 'intense fatigue', 'feel tired', 'stomach upset', 'muscles are twitching',
    'appetite is only a little diminished', 'sleepy', 'syndrome', 'delirium', 'viral fatigue chronic fatigue syndrome',
    'temperature spike', 'green / yellow phlegm', 'significant trouble sleeping', 'sleep problem', 'viral fatigue',
    'trouble sleeping', 'panic attack', 'nicotine withdrawal symptoms', 'chest tightness and heavyness',
    'feeling somethings in my lungs', 'backache', 'hives', 'tongue swelled', 'trouble breathing', 'lack of taste',
    'mouth was burned', 'covid toes', 'blood clots', 'allergy like redness around the toes nails',
    'redness around the toes', 'severe stomach pain', 'sickness', 'lathargic', 'heavyness',
    'slight pain when taking a very deep breathe', 'back ache', 'nauseau', 'lack of taste / smell', 'ticklish throat',
    'chest has been hurting', 'cant take a satisfying breath', 'heart burn', 'sick', 'unwell', 'wheezing',
    'painful throat', 'discomfort on swallowing', 'pains', '100 degree fever', 'high temp', 'loss of taste and smell',
    'temperature', 'chestiness', 'diahrrea', 'arm ache', 'leg aches', 'persistant cough',
    'discomfort in chest when breathing']